### PR TITLE
Remove underscore from _openConnection and _closeConnection. #263

### PR DESCRIPTION
**Pull request by kommen**
Should fix https://github.com/square/SocketRocket/issues/263

Our app containing this patch was approved successfully by App Store Review.

### CODE REVIEW

**Comment by brandons** [comment]
Thanks @kommen. @dfed @ dnkoutso can we get this merged?

**Comment by dfed** [comment]
@brandons you'll need to sign our [CLA](https://docs.google.com/a/squareup.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1) before we can merge this.

**Comment by kommen** [comment]
@dfed I just signed the CLA

**Comment by dfed** [comment]
Thanks @kommen and apologies for the mixup above. Merging. I'll bump the pod spec and publish in the next few minutes.

**Pull request merged**
