### PR TITLE
Add dynamic framework for iOS

### PR DESCRIPTION
**Pull request by mogstad**
Added new schema “SocketRocket-iOS”, a dynamic framework with deployment target for iOS. Allows SocketRocket to be installed via Carthage (tested with Carthage v0.9.1)

(CLA signed)

### CODE REVIEW

**Comment by dfed** [comment]
Thanks for the PR! I dig it. Only one request: please add the following line to the `.travis.yml` file to prevent future PRs from breaking Carthage:
```
- xcodebuild -project Valet.xcodeproj -scheme "SocketRocket-iOS" -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build
```

@mikelikespie anything in here that looks fishy to you? You know how SocketRocket builds better than I.

**Comment by mogstad** [comment]
:+1: Forced pushed the branch

**Comment by dfed** [comment]
Awesome! And thanks for fixing my copy/paste from Valet :)

**Comment by pettigree** [comment]
Thanks for this!!

**Comment by mogstad** [comment]
> Is it as simple as needing the platform name appended the end of the scheme name and bumping the iOS Deployment Target?

No, the name of the schema is irrelevant. The required changes includes a bunch of build settings, but mostly setting `SUPPORTED_PLATFORMS` to `iphonesimulator iphoneos` and setting `SDKROOT` to `iphoneos`. This is set up for you if you add a dynamic framwork template from Xcode.

**Comment by pettigree** [comment]
Thanks for the info!

**Comment by mutexre** [comment]
Perhaps iOS framework is better called SocketRocketIOS in the similar fashion to SocketRocketOSX?

**Comment by mogstad** [comment]
I tendt to agree, but I didn’t do it as I find it awkward uppercasing the i in `iOS`, and not uppercasing it is just as awkward. @dfed got any preferences?

**Comment by dfed** [comment]
No preference, though I agree that iOS capitalization is always awkward.

**Comment by martinmroz** [comment]
You can side-step the whole capitalization issue by calling it "SocketRocketMobile" ^_^

**Comment by pettigree** [comment]
@mogstad in the interim of this getting merged, is there a way that I can build locally for all schemes? when using `carthage build --no-skip-current` I don't see the iOS variant being built from the SocketRocket scheme, only OS X.

**Comment by mogstad** [comment]
Works over here, which version of carthage are you using? Are you sure you’ve checked out my repo and has checked out the carthage branch?

**Comment by pettigree** [comment]
I'm a lamewad and didn't notice that there was a carthage branch in your repo @mogstad thanks again!!!

**Pull request merged**
