### PR TITLE
Added ability to provide cookies for the web socket connection

### PR DESCRIPTION
**Pull request by jmkk**
For web sockets used behind an already authenticated HTTP(S) session you might want to provide the session cookie or other cookies appropriate for the web socket connection (for example Spring's SessionID when connecting to a Spring-authentication java backend server).

Sample usage for the clients could be:

```
[[self webSocket] setRequestCookies:[[NSHTTPCookieStorage sharedHTTPCookieStorage] cookies]];
```

Note that you might want to limit the cookies provided to the WebSocket based on the URL (cookiesForURL:).

### CODE REVIEW

**Comment by snowyote** [comment]
+1

**Comment by wildthink** [comment]
+1 Anything I/we can do to get this one in?

**Comment by vigneshv59** [comment]
+1

**Comment by wollodev** [comment]
+1

**Comment by vigneshv59** [comment]
Can something be done to merge this commit?

**Comment by ioncreature** [comment]
+1

**Comment by deshaser** [comment]
Guys, I need this feature! Please merge it to master.

**Comment by dfed** [comment]
Thanks for the PR folks! Sorry for taking so long to review this. Can you please sign our (CLA)[https://docs.google.com/a/squareup.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1] and rebase master? Once the conflicts are fixed and the CLA is signed, we'll merge this.

**Comment by msgilligan** [comment]
@jmkk Are you around to rebase to master and sign the CLA?

**Comment by jmkk** [comment]
Not sure if that worked - it's been a while since I created that PR. Let me know @dfed 
Otherwise I'll cherry pick it to the latest master and create a new PR?

**Comment by dfed** [comment]
@jmkk thanks for the fast response! Looks like there are still conflicts. Please do cherry-pick onto master and open a new PR. If you do that (and sign the CLA if you haven't already), I'll merge tonight. Thanks!

**Comment by jmkk** [comment]
@dfed Created a fresh PR https://github.com/square/SocketRocket/pull/280 and signed CLA

**Pull request closed without merging**
