### PR TITLE
Fix iOS 9 / El Cap build error due to non-nullability changes

### PR DESCRIPTION
**Pull request by james-howard**

### CODE REVIEW

**Comment by dfed** [comment]
Thanks! Have you signed the CLA? squ.re/sign-the-cla

**Comment by james-howard** [comment]
Signed.

**Comment by dfed** [comment]
Awesome! Can you rebase master so we can get a CI build?

**Comment by james-howard** [comment]
Rebased.

**Comment by dfed** [comment]
Thanks! LGTM.

**Pull request merged**
